### ISSUE TITLE
Milestone 4 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/suicide_indicator_r#67]
> **Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, **please feel free to ask questions in this issue thread.**

---

## 1. Submission instructions
rubric={mechanics:4}
Well done!

## 2. Improving your app
rubric={mechanics:20}
Well done!

#### 2.1 - Testing
rubric={mechanics:5, accuracy:5}

- [ ] There are less than 3 `test_that()` statements in the file `tests/testthat/test-shinytest2.R` **-4 mechanics**

#### 2.2 Continous Integration and Deployment
rubric={mechanics:5, accuracy:5}

- [ ] There are no badges in the `README.md`. There should be one workflow badge **-5 mechanics**

- [ ] The deployment workflow `deploy_app.yaml` is not passing. **-5 accuracy**

## 3. Tie it all together and deliver a production ready app
rubric={mechanics:20, accuracy:20, viz:10}

**You are creating your production-ready Shiny app this week!**
- [ ] The apps's reactivity isn't working as expected (for example, if it is a dropdown menu, modifiying the option doesn't change the related plot)  **-4 accuracy**

- [ ] There are axis labels that are still the names of the dataset variable and/or there are no legends to understand plot or maps color categories. **-3 viz**

Comments:
-The Suicide Count by Age group plot is not reacting to the filter of Gender.
-The axis labels on the Suicide Count by Age group plot are incorrect.

**Improve the user feedback**
Well done!

**Improve the documentation**
Well done!

## 4. Reflection
rubric={reasoning:6}
Well done!

**Comment by tieandrews** [comment]
Hi @negsadr thanks for the feedback. 

One piece I think you might have missed is at the time of submission test/deploy runners were both passing, see screenshot below. You may have seen a previously failed one.
![image](https://user-images.githubusercontent.com/29762703/228130765-cc525582-163e-4110-b3df-447c262383dd.png)

Thanks for reviewing that.

**Comment by flor14** [comment]
Well done implementing the Dumbbell Plot! For your portfolio: pay attention that it is something wrong with the axis of that plot.
Congratulations!
